-- AlterTable
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "supplierPriceCents" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "supplierCommissionRateBps" INTEGER NOT NULL DEFAULT 1000;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "affiliateMarginCents" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "affisellCommissionRateBps" INTEGER NOT NULL DEFAULT 1200;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "supplierPayoutCents" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "affiliateStripeAccountId" TEXT;

-- CreateIndex
CREATE INDEX IF NOT EXISTS "Order_affiliateId_idx" ON "Order"("affiliateId");
