/**
 * Validation of what a BROWSER may send to the ingestion endpoint (S3), and of the batch envelope.
 *
 * A browser is an untrusted witness: it may report what a visitor saw or did (behavioral events), nothing else.
 *  - only events the registry marks `clientEmittable` are accepted — never a purchase, refund or return;
 *  - the schema is STRICT: userId, anonymousId, creatorId, supplierId, orderId, country, channel… are not fields a
 *    browser can set; the server derives them (session, consent cookie, edge header, attribution rules);
 *  - validation is per event, so one bad event never costs the other nineteen.
 *
 * Pure (no Prisma) — usable from route handlers and tests.
 */
import { z } from "zod"

import { CLIENT_EMITTABLE_EVENT_NAMES } from "@/lib/events/names"
import { sanitizeId, sanitizeSessionId } from "@/lib/events/sanitize"

export const MAX_BATCH_EVENTS = 20
/** Largest request body the endpoint should even parse (bytes). */
export const MAX_BATCH_BYTES = 16_000

const id = z.string().refine((v) => sanitizeId(v) !== null, "invalid id")
const sessionId = z.string().refine((v) => sanitizeSessionId(v) !== null, "invalid session id")

export const clientEventSchema = z.strictObject({
  /** Idempotency key, generated by the browser: a retried or double-fired event is stored once. */
  eventId: z.uuid(),
  name: z.enum(CLIENT_EMITTABLE_EVENT_NAMES),
  /** Browser clock in ms since epoch — only a hint: the server clamps it. */
  clientTs: z.number().int().optional(),
  sessionId: sessionId.optional(),
  productId: id.optional(),
  listingId: id.optional(),
  durationMs: z.number().int().min(0).max(600_000).optional(),
  /** Raw: it is cut down to the whitelisted, sanitised keys of the event (see properties.ts). */
  properties: z.record(z.string().max(64), z.unknown()).optional(),
})

export type ClientEvent = z.infer<typeof clientEventSchema>

export type ClientBatchResult = {
  events: ClientEvent[]
  /** Events dropped for being malformed, by reason. */
  rejected: number
  /** The envelope itself was unusable (not an object / no `events` array / too many events). */
  envelopeError: "not_an_object" | "no_events" | "too_many_events" | null
}

/** Parses a decoded request body. Never throws. */
export function parseClientBatch(body: unknown): ClientBatchResult {
  if (!body || typeof body !== "object" || Array.isArray(body)) {
    return { events: [], rejected: 0, envelopeError: "not_an_object" }
  }
  const raw = (body as { events?: unknown }).events
  if (!Array.isArray(raw) || raw.length === 0) {
    return { events: [], rejected: 0, envelopeError: "no_events" }
  }
  if (raw.length > MAX_BATCH_EVENTS) {
    return { events: [], rejected: raw.length, envelopeError: "too_many_events" }
  }
  const events: ClientEvent[] = []
  let rejected = 0
  for (const item of raw) {
    const parsed = clientEventSchema.safeParse(item)
    if (parsed.success) events.push(parsed.data)
    else rejected += 1
  }
  return { events, rejected, envelopeError: null }
}

export function isBatchSizeAcceptable(byteLength: number): boolean {
  return Number.isFinite(byteLength) && byteLength > 0 && byteLength <= MAX_BATCH_BYTES
}
