/** Affisell marketplace taxonomy — English labels (no third-party trademarks).
 * @deprecated Use DB `Category` tree (`/api/categories`) — kept for legacy import allowlist until backfill completes.
 */
export const AFFISELL_CATEGORIES = [
  "All Departments",
  "Voice Skills",
  "Smart Devices",
  "Fresh Market",
  "Affisell Haul",
  "Pharmacy",
  "Appliances",
  "Apps & Games",
  "Arts, Crafts & Sewing",
  "Automotive",
  "Baby",
  "Beauty & Personal Care",
  "Books",
  "CDs & Vinyl",
  "Cell Phones & Accessories",
  "Clothing, Shoes & Jewelry",
  "Collectibles & Fine Art",
  "Computers",
  "Daily Deals",
  "Digital Music",
  "Electronics",
  "Garden & Outdoor",
  "Gift Cards",
  "Grocery & Gourmet Food",
  "Handmade",
  "Health & Household",
  "Home & Kitchen",
  "Industrial & Scientific",
  "E-Reader Store",
  "Luggage & Travel Gear",
  "Luxury Stores",
  "Movies & TV",
  "Musical Instruments",
  "Office Products",
  "Pet Supplies",
  "Premium Beauty",
  "Streaming Video",
  "Smart Home",
  "Software",
  "Sports & Outdoors",
  "Subscribe & Save",
  "Tools & Home Improvement",
  "Toys & Games",
  "Video Games",
] as const

export type AffisellCategory = (typeof AFFISELL_CATEGORIES)[number]
