/** Shared Affisell brand / role surface classes (see `app/globals.css`). */
export const affisellBrand = {
  headerShell: "affisell-header-shell",
  headerMesh: "affisell-header-mesh",
  gradientBar: "affisell-gradient-bar",
  badgeBrand: "affisell-badge affisell-badge--brand",
  badgeBuyer: "affisell-badge affisell-badge--buyer",
  badgeSupplier: "affisell-badge affisell-badge--supplier",
  badgeAffiliate: "affisell-badge affisell-badge--affiliate",
  quickLink: "group affisell-quick-link",
  quickLinkIconBrand: "affisell-quick-link__icon affisell-quick-link__icon--brand",
  quickLinkIconSupplier: "affisell-quick-link__icon affisell-quick-link__icon--supplier",
  quickLinkIconAffiliate: "affisell-quick-link__icon affisell-quick-link__icon--affiliate",
  quickLinkIconBuyer: "affisell-quick-link__icon affisell-quick-link__icon--buyer",
  eyebrowBrand: "text-brand dark:text-brand-light",
  eyebrowBuyer: "text-buyer dark:text-buyer-light",
  ctaBrand: "epoxy-cta bg-brand text-white shadow-md shadow-brand/25 hover:bg-brand-hover",
  /** Transparent glossy epoxy resin system */
  epoxyPage: "affisell-epoxy-page",
  epoxyCanvas: "affisell-epoxy-canvas",
  epoxySurface: "epoxy-surface",
  epoxySurfaceLight: "epoxy-surface epoxy-surface--light",
  epoxyChip: "epoxy-chip",
  epoxyPanel: "epoxy-surface rounded-2xl",
  epoxyCta: "epoxy-cta",
  epoxyGestureBadge: "epoxy-gesture-badge rounded-2xl px-3 py-2",
  epoxyActionBtn: "epoxy-action-btn epoxy-chip",
  epoxyActionBuy: "epoxy-action-btn epoxy-action-btn--buy",
  epoxyActionCart: "epoxy-action-btn epoxy-action-btn--cart",
  epoxyActionDrop: "epoxy-action-btn epoxy-action-btn--drop",
  epoxyToast: "epoxy-toast epoxy-chip",
  brandWordmark: "affisell-brand-wordmark affisell-brand-wordmark--sm",
} as const
