/**
 * Agents d'achat Chine — données pures (client-safe, pas de Prisma).
 * Couvre 1688, Taobao, Tmall, JD.com, Weidian, Pinduoduo, Xianyu et usines directes (B2B).
 */

export const AGENTS = [
  {
    id: "superbuy",
    name: "Superbuy",
    fee: "8%",
    processing: "2-4 jours",
    deliveryEU: "9-17 jours",
    qcPhotos: "3 gratuites",
    storage: "90 jours",
    domesticShipping: "Payant",
    support: "Ticket 24h",
    platforms: ["1688", "Taobao", "Tmall", "JD.com", "Weidian", "Pinduoduo", "Xianyu", "Usines"],
    strengths: ["Qualité", "Fiabilité", "B2B"],
    bestFor: "Échantillons et usines – QC sérieux, 13 ans, gère les fournisseurs directs",
    priceLevel: "€€€",
    speedLevel: "moyen",
    qualityLevel: "élevé",
    note: "Accepte les contacts usine WeChat, négociation MOQ",
  },
  {
    id: "anovabuy",
    name: "Anovabuy",
    fee: "5%",
    processing: "1-3 jours",
    deliveryEU: "7-12 jours",
    qcPhotos: "5 gratuites",
    storage: "180 jours",
    domesticShipping: "Gratuit",
    support: "WhatsApp 24/7",
    platforms: ["1688", "Taobao", "Tmall", "JD.com", "Weidian", "Pinduoduo", "Usines"],
    strengths: ["Prix", "B2B", "Gros volumes"],
    bestFor: "Marques et usines – prix B2B, livraison domestique gratuite",
    priceLevel: "€",
    speedLevel: "rapide",
    qualityLevel: "élevé",
    note: "Idéal pour négocier direct usine, pas de frais cachés",
  },
  {
    id: "oopbuy",
    name: "Oopbuy",
    fee: "5%",
    processing: "1-2 jours",
    deliveryEU: "7-14 jours",
    qcPhotos: "3 gratuites",
    storage: "90 jours",
    domesticShipping: "Payant",
    support: "Chat live",
    platforms: ["1688", "Taobao", "Tmall", "Weidian", "Pinduoduo", "Xianyu"],
    strengths: ["Vitesse", "UI moderne"],
    bestFor: "Dropshipping multi-plateformes",
    priceLevel: "€€",
    speedLevel: "très rapide",
    qualityLevel: "moyen",
  },
  {
    id: "litbuy",
    name: "Litbuy",
    fee: "4%",
    processing: "24h",
    deliveryEU: "6-12 jours",
    qcPhotos: "8 gratuites",
    storage: "120 jours",
    domesticShipping: "Gratuit >¥99",
    support: "Discord",
    platforms: ["Weidian", "Taobao", "1688", "Tmall"],
    strengths: ["Vitesse", "Weidian"],
    bestFor: "Remplace Pandabuy – spécialiste Weidian et sneakers",
    priceLevel: "€",
    speedLevel: "très rapide",
    qualityLevel: "moyen",
  },
  {
    id: "cssbuy",
    name: "Cssbuy",
    fee: "3-5%",
    processing: "2-3 jours",
    deliveryEU: "8-15 jours",
    qcPhotos: "3 gratuites",
    storage: "365 jours",
    domesticShipping: "Payant",
    support: "Ticket",
    platforms: ["1688", "Taobao", "Tmall", "JD.com", "Weidian", "Xianyu"],
    strengths: ["Prix", "Stockage long"],
    bestFor: "Budget serré – frais les plus bas",
    priceLevel: "€",
    speedLevel: "moyen",
    qualityLevel: "moyen",
  },
  {
    id: "sugargoo",
    name: "Sugargoo",
    fee: "4-6%",
    processing: "2-4 jours",
    deliveryEU: "8-16 jours",
    qcPhotos: "3 gratuites",
    storage: "180 jours",
    domesticShipping: "Payant",
    support: "Email",
    platforms: ["1688", "Taobao", "Tmall", "JD.com", "Pinduoduo"],
    strengths: ["Groupage", "Prix"],
    bestFor: "Grouper plusieurs fournisseurs",
    priceLevel: "€€",
    speedLevel: "moyen",
    qualityLevel: "moyen",
  },
]

export const PLATFORMS = [
  "1688",
  "Taobao",
  "Tmall",
  "JD.com",
  "Weidian",
  "Pinduoduo",
  "Xianyu",
  "Usines",
]
