/**
 * Affisell canonical department taxonomy (parents + sub-labels).
 * Kept in sync with `prisma/seed-taxonomy.ts` — import `AFFISELL_CATEGORY_TAXONOMY` from here in the seeder.
 */

export type AffisellTaxonomyDept = {
  readonly name: string
  readonly slug: string
  readonly icon: string
  readonly order: number
  readonly subs: readonly string[]
}

export const AFFISELL_CATEGORY_TAXONOMY = [
  {
    name: "Electronics",
    slug: "electronics",
    icon: "📱",
    order: 1,
    subs: [
      "Cell Phones & Accessories",
      "Computers & Tablets",
      "TV & Video",
      "Audio & Headphones",
      "Camera & Photo",
      "Video Games",
      "Wearable Technology",
      "GPS & Navigation",
      "Office Electronics",
      "Electronic Components",
      "Smart Home",
      "Printers & Scanners",
    ],
  },
  {
    name: "Home & Kitchen",
    slug: "home-kitchen",
    icon: "🏡",
    order: 2,
    subs: [
      "Furniture",
      "Kitchen & Dining",
      "Bedding & Bath",
      "Home Decor",
      "Storage & Organization",
      "Patio, Lawn & Garden",
      "Lighting & Ceiling Fans",
      "Appliances",
      "Vacuums & Floor Care",
      "Event & Party Supplies",
      "Cookware & Bakeware",
      "Large Appliances",
    ],
  },
  {
    name: "Beauty & Personal Care",
    slug: "beauty",
    icon: "💄",
    order: 3,
    subs: [
      "Makeup",
      "Skin Care",
      "Hair Care",
      "Fragrance",
      "Personal Care",
      "Tools & Accessories",
      "Oral Care",
      "Shaving & Hair Removal",
    ],
  },
  {
    name: "Men's Fashion",
    slug: "mens-fashion",
    icon: "👔",
    order: 4,
    subs: ["Clothing", "Shoes", "Watches", "Accessories", "Activewear", "Swimwear", "Underwear & Sleepwear"],
  },
  {
    name: "Women's Fashion",
    slug: "womens-fashion",
    icon: "👗",
    order: 5,
    subs: [
      "Clothing",
      "Shoes",
      "Handbags & Wallets",
      "Jewelry",
      "Watches",
      "Activewear",
      "Lingerie & Sleepwear",
      "Accessories",
    ],
  },
  {
    name: "Sports & Outdoors",
    slug: "sports",
    icon: "⚽",
    order: 6,
    subs: [
      "Exercise & Fitness",
      "Outdoor Recreation",
      "Team Sports",
      "Cycling",
      "Fishing",
      "Hunting",
      "Camping & Hiking",
      "Water Sports",
      "Golf",
      "Yoga & Pilates",
      "Winter Sports",
      "Racket Sports",
    ],
  },
  {
    name: "Toys & Games",
    slug: "toys",
    icon: "🧸",
    order: 7,
    subs: [
      "Action Figures & Statues",
      "Board Games",
      "Dolls & Accessories",
      "Building Toys",
      "Educational Toys",
      "Puzzles",
      "Outdoor Play",
      "Stuffed Animals",
    ],
  },
  {
    name: "Books",
    slug: "books",
    icon: "📚",
    order: 8,
    subs: [
      "Fiction",
      "Non-Fiction",
      "Children Books",
      "Textbooks",
      "Comics & Graphic Novels",
      "Cookbooks",
      "E-Books",
    ],
  },
  {
    name: "Automotive",
    slug: "automotive",
    icon: "🚗",
    order: 9,
    subs: [
      "Car Care",
      "Car Electronics",
      "Tools & Equipment",
      "Replacement Parts",
      "Interior Accessories",
      "Exterior Accessories",
      "Motorcycle & Powersports",
    ],
  },
  {
    name: "Pet Supplies",
    slug: "pet-supplies",
    icon: "🐕",
    order: 10,
    subs: ["Dog Supplies", "Cat Supplies", "Fish & Aquatic Pets", "Bird Supplies", "Small Animals", "Reptiles", "Horse Supplies"],
  },
  {
    name: "Office Products",
    slug: "office",
    icon: "📎",
    order: 11,
    subs: [
      "Office Electronics",
      "School Supplies",
      "Office Furniture",
      "Paper & Notebooks",
      "Writing Supplies",
      "Printer Ink & Toner",
    ],
  },
  {
    name: "Health & Household",
    slug: "health",
    icon: "💊",
    order: 12,
    subs: [
      "Vitamins & Supplements",
      "Household Supplies",
      "Medical Supplies",
      "Baby Care",
      "Health Monitors",
      "Sports Nutrition",
    ],
  },
  {
    name: "Baby Products",
    slug: "baby",
    icon: "🍼",
    order: 13,
    subs: ["Strollers & Car Seats", "Nursery", "Diapering", "Feeding", "Baby & Toddler Toys", "Baby Clothing"],
  },
  {
    name: "Tools & Home Improvement",
    slug: "tools",
    icon: "🔨",
    order: 14,
    subs: [
      "Power Tools",
      "Hand Tools",
      "Hardware",
      "Paint & Wall Treatment",
      "Electrical",
      "Plumbing",
      "Safety & Security",
    ],
  },
  {
    name: "Industrial & Scientific",
    slug: "industrial",
    icon: "⚙️",
    order: 15,
    subs: ["Lab & Scientific Products", "Janitorial Supplies", "Food Service", "Material Handling", "Test, Measure & Inspect"],
  },
  {
    name: "Arts, Crafts & Sewing",
    slug: "arts-crafts",
    icon: "🎨",
    order: 16,
    subs: [
      "Painting & Drawing",
      "Fabric & Sewing",
      "Scrapbooking",
      "Knitting & Crochet",
      "Beading & Jewelry Making",
      "Printmaking",
      "Ceramics & Modeling",
    ],
  },
  {
    name: "Music, Movies & TV",
    slug: "music",
    icon: "🎵",
    order: 17,
    subs: ["Musical Instruments", "CDs & Vinyl", "Movies & TV Shows", "Sheet Music", "Studio & Recording"],
  },
  {
    name: "Collectibles & Fine Art",
    slug: "collectibles",
    icon: "🖼️",
    order: 18,
    subs: ["Collectible Cards", "Coins & Currency", "Sports Memorabilia", "Antiques", "Fine Art"],
  },
  {
    name: "Grocery & Gourmet Food",
    slug: "grocery",
    icon: "🛒",
    order: 19,
    subs: [
      "Beverages",
      "Snacks",
      "Pantry Staples",
      "Fresh Food",
      "International Foods",
      "Gourmet Gifts",
      "Organic Foods",
      "Plant-Based & Vegan",
      "Gluten-Free",
      "Keto & Low Carb",
    ],
  },
  {
    name: "Handmade Products",
    slug: "handmade",
    icon: "✋",
    order: 20,
    subs: ["Handmade Jewelry", "Handmade Home Decor", "Handmade Clothing", "Handmade Art"],
  },
  {
    name: "Digital Content & Services",
    slug: "digital",
    icon: "⚡",
    order: 21,
    subs: ["Software", "Video Games Digital", "E-Books", "Online Courses"],
  },
  {
    name: "Travel & Luggage",
    slug: "travel",
    icon: "✈️",
    order: 22,
    subs: [
      "Luggage & Suitcases",
      "Travel Accessories",
      "Packing Organisers",
      "Travel Adapters",
      "Neck Pillows & Comfort",
    ],
  },
  {
    name: "Party & Costumes",
    slug: "party-costumes",
    icon: "🎊",
    order: 23,
    subs: ["Party Decorations", "Disposable Tableware", "Adult Costumes", "Kids Costumes", "Wedding Supplies"],
  },
  {
    name: "Major Appliances",
    slug: "major-appliances",
    icon: "❄️",
    order: 24,
    subs: ["Refrigeration", "Laundry", "Dishwashers", "Built-In Cooking", "Range Hoods"],
  },
  {
    name: "Cycling & Scooters",
    slug: "cycling-scooters",
    icon: "🚲",
    order: 25,
    subs: ["Bicycles", "Bike Parts", "Electric Scooters", "Protective Gear", "Bike Racks"],
  },
  {
    name: "Boating & Marine",
    slug: "boating-marine",
    icon: "⛵",
    order: 26,
    subs: ["Marine Safety", "Anchoring & Mooring", "Engine Maintenance", "Navigation"],
  },
  {
    name: "School & Education",
    slug: "school-education",
    icon: "🎓",
    order: 27,
    subs: ["Classroom Supplies", "Teachers Resources", "Science Lab", "Art Class", "Calculators"],
  },
  {
    name: "Equestrian & Farm",
    slug: "equestrian-farm",
    icon: "🐴",
    order: 28,
    subs: ["Riding Apparel", "Tack & Saddlery", "Stable Supplies", "Poultry & Feed"],
  },
  {
    name: "Software & Apps",
    slug: "software-apps",
    icon: "💾",
    order: 29,
    subs: ["PC Software", "Mac Software", "Antivirus", "Creative Software", "Game Codes"],
  },
  {
    name: "B2B & Professional Supply",
    slug: "b2b-professional",
    icon: "🏢",
    order: 30,
    subs: [
      "Office & Facility Consumables",
      "Hospitality & Catering Trade",
      "Retail Packaging",
      "Medical & Care Trade",
      "Workshop & Fleet",
      "Corporate Gifts",
      "Commercial Kitchen Equipment",
    ],
  },
  {
    name: "Sustainable Living",
    slug: "sustainable-living",
    icon: "♻️",
    order: 31,
    subs: ["Reusables", "Refill Personal Care", "Solar Portable", "Water Filters Home"],
  },
  {
    name: "Senior & Adaptive Aids",
    slug: "senior-adaptive",
    icon: "🦯",
    order: 32,
    subs: ["Mobility Aids", "Bathroom Safety", "Dressing Aids", "Low Vision & Hearing"],
  },
  {
    name: "Pop Culture & Anime Merch",
    slug: "pop-culture-anime",
    icon: "🎌",
    order: 33,
    subs: ["Figures & Statues", "Pins & Keychains", "Posters & Wall Art", "Convention Accessories"],
  },
] as const satisfies readonly AffisellTaxonomyDept[]

/** Flat "Parent > Subcategory" labels used in prompts and UI hints. */
export const CATEGORIES_AFFISELL: readonly string[] = AFFISELL_CATEGORY_TAXONOMY.flatMap((d) =>
  d.subs.map((sub) => `${d.name} > ${sub}`)
)
